# this file is located in /etc/ansible/windows_project
# windows_project is a fav name
# hosts: win, name 'win' here is my windows server group name
- name: Change the hostname to HQ-IIS
  hosts: win
  ansible.windows.win_hostname:
    name: HQ-IIS
  register: res

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required
